version: "3.7"

services:
  web:
    image: mempool/frontend:latest
    # container_name:
    environment:
      FRONTEND_HTTP_PORT: 8080
      BACKEND_MAINNET_HTTP_HOST: api
    # volumes:
    # secrets:
    # networks:
    ports:
      - 80:8080
    depends_on:
      db:
        condition: service_healthy
    restart: always
    init: true
    user: "1000:1000"

  api:
    image: mempool/backend:latest
    # container_name:
    env_file: api.env
    volumes:
      - api-data:/backend/cache:rw
    # secrets:
    # networks:
    # ports:
    depends_on:
      db:
        condition: service_healthy
    restart: always
    init: true
    user: "1000:1000"
    post_start:
      - command: ["chown", "-R", "1000:1000", "/backend/cache"]
        user: "root"

  db:
    image: mariadb:10.5.21
    # container_name:
    environment:
      MYSQL_DATABASE: mempool
      MYSQL_USER: mempool
      MYSQL_PASSWORD: mempool
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql:rw
    # secrets:
    # networks:
    # ports:
    # depends_on:
    restart: always
    init: true
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
    post_start:
      - command: ["chown", "-R", "1000:1000", "/var/lib/mysql"]
        user: "root"

volumes:
  db-data:
  api-data: